---
# See: http://docs.ansible.com/ansible/intro_configuration.html#pipelining
- name: Set a sudoers file to disable tty
  template: >
    src=disable-requiretty.j2
    dest=/etc/sudoers.d/disable-requiretty
    owner=root group=root mode=0440
    validate="visudo -cf %s"
  sudo: True
